apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jqjscx9mm-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jqjscx9mm-java-springboot-gitops